package com.mr.model;

import java.lang.reflect.Method;

import org.springframework.beans.factory.support.MethodReplacer;

import sun.text.normalizer.Replaceable;

public class Jasper implements MethodReplacer {

	public Object reimplement(Object obj, Method method, Object[] args) throws Throwable {
		
		
		System.out.println("Report generated by :: Jasper");
		return obj;
	}

	
	
}
